/**
 * Codegen: split-openapi.ts
 *
 * Splits the monolithic OpenAPI-generated TypeScript file into per-resource
 * files. Run via `pnpm codegen`.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname, '../../..');
const GENERATED_DIR = join(ROOT, 'packages/api-types/src/generated/http');

interface ResourceSplit {
  readonly file: string;
  readonly resource: string;
}

const RESOURCE_MAP: readonly ResourceSplit[] = [
  { file: 'common.ts', resource: 'common' },
  { file: 'member.ts', resource: 'member' },
  { file: 'profile.ts', resource: 'profile' },
  { file: 'content.ts', resource: 'content' },
  { file: 'engagement.ts', resource: 'engagement' },
  { file: 'network.ts', resource: 'network' },
  { file: 'outreach.ts', resource: 'outreach' },
  { file: 'opportunity.ts', resource: 'opportunity' },
  { file: 'analytics.ts', resource: 'analytics' },
  { file: 'approval.ts', resource: 'approval' },
  { file: 'admin.ts', resource: 'admin' },
  { file: 'briefing.ts', resource: 'briefing' },
  { file: 'kb.ts', resource: 'kb' },
];

function extractResourceBlock(content: string, resource: string): string {
  const headerMarker = `From schemas/openapi/api-gateway.yaml — ${capitalize(resource)} resources.`;
  const startIdx = content.indexOf(headerMarker);
  if (startIdx === -1) return '';
  const afterHeader = content.indexOf('*/', startIdx) + 2;
  const nextHeader = content.indexOf('\n/*', afterHeader);
  return nextHeader === -1
    ? content.slice(afterHeader).trim()
    : content.slice(afterHeader, nextHeader).trim();
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function main() {
  if (!existsSync(GENERATED_DIR)) {
    mkdirSync(GENERATED_DIR, { recursive: true });
  }

  // The monolithic file is generated by `openapi-typescript` to
  // `packages/api-types/src/generated/http/index.ts`. Here we split it.
  const monolithPath = join(GENERATED_DIR, 'index.ts');
  const content = readFileSync(monolithPath, 'utf-8');

  for (const { file, resource } of RESOURCE_MAP) {
    const block = extractResourceBlock(content, resource);
    if (!block) {
      console.warn(`[split-openapi] no block found for ${resource}`);
      continue;
    }
    writeFileSync(join(GENERATED_DIR, file), block, 'utf-8');
    console.log(`[split-openapi] wrote ${file} (${block.length} bytes)`);
  }
}

main();
