/**
 * Trace ID — the support-debuggability token.
 *
 * Every API mutation must include `x-trace-id`. The ID is generated by the
 * API client, attached to the request, and returned in the response. The
 * `<TraceIdBadge>` component renders it on hover for any failed action.
 */

import type { TraceId } from '../runtime/brand';

export interface TracedRequest {
  traceId: TraceId;
  idempotencyKey?: string;
  occurredAt: string;
}

export interface TracedResponse<T> {
  data: T;
  traceId: TraceId;
  receivedAt: string;
}
