/**
 * Tailwind preset for @lcc/tokens.
 *
 * Extends Tailwind with the OKESON-LCC design tokens: colors, spacing,
 * typography, radius, shadow, motion, and the risk-tier palette.
 *
 * Apps consume via `presets: [require('@lcc/tokens/tailwind')]`.
 */

const cssVar = (name) => `var(--${name})`;

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  theme: {
    extend: {
      colors: {
        background: cssVar('color-background'),
        foreground: cssVar('color-foreground'),
        muted: cssVar('color-muted'),
        'muted-foreground': cssVar('color-muted-foreground'),
        card: cssVar('color-card'),
        'card-foreground': cssVar('color-card-foreground'),
        popover: cssVar('color-popover'),
        'popover-foreground': cssVar('color-popover-foreground'),
        border: cssVar('color-border'),
        input: cssVar('color-input'),
        ring: cssVar('color-ring'),
        primary: cssVar('color-primary'),
        'primary-foreground': cssVar('color-primary-foreground'),
        secondary: cssVar('color-secondary'),
        'secondary-foreground': cssVar('color-secondary-foreground'),
        accent: cssVar('color-accent'),
        'accent-foreground': cssVar('color-accent-foreground'),
        destructive: cssVar('color-destructive'),
        'destructive-foreground': cssVar('color-destructive-foreground'),
        success: cssVar('color-success'),
        'success-foreground': cssVar('color-success-foreground'),
        warning: cssVar('color-warning'),
        'warning-foreground': cssVar('color-warning-foreground'),
        info: cssVar('color-info'),
        'info-foreground': cssVar('color-info-foreground'),
        'tier-1': cssVar('color-tier-1'),
        'tier-2': cssVar('color-tier-2'),
        'tier-3': cssVar('color-tier-3'),
        'tier-4': cssVar('color-tier-4'),
        'tier-5': cssVar('color-tier-5'),
        'restricted': cssVar('color-restricted'),
      },
      borderRadius: {
        sm: cssVar('radius-sm'),
        md: cssVar('radius-md'),
        lg: cssVar('radius-lg'),
        full: cssVar('radius-full'),
      },
      spacing: {
        0.5: '0.125rem',
        1: '0.25rem',
        1.5: '0.375rem',
        2: '0.5rem',
        2.5: '0.625rem',
        3: '0.75rem',
        3.5: '0.875rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
        7: '1.75rem',
        8: '2rem',
        9: '2.25rem',
        10: '2.5rem',
        11: '2.75rem',
        12: '3rem',
        14: '3.5rem',
        16: '4rem',
        20: '5rem',
        24: '6rem',
        28: '7rem',
        32: '8rem',
        36: '9rem',
        40: '10rem',
        44: '11rem',
        48: '12rem',
        52: '13rem',
        56: '14rem',
        60: '15rem',
        64: '16rem',
        72: '18rem',
        80: '20rem',
        96: '24rem',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.875rem', { lineHeight: '1.25rem' }],
        base: ['1rem', { lineHeight: '1.5rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1.16' }],
      },
      boxShadow: {
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        DEFAULT: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
        md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
        lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
        xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
      },
      transitionDuration: {
        fast: '120ms',
        base: '200ms',
        slow: '320ms',
      },
      transitionTimingFunction: {
        'ease-out': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'ease-in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      animation: {
        'accordion-down': 'accordion-down 200ms cubic-bezier(0.16, 1, 0.3, 1)',
        'accordion-up': 'accordion-up 200ms cubic-bezier(0.16, 1, 0.3, 1)',
        'pulse-subtle': 'pulse-subtle 2400ms ease-in-out infinite',
        'fade-in': 'fade-in 200ms ease-out',
        'fade-out': 'fade-out 200ms ease-out',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'pulse-subtle': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.6' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'fade-out': {
          from: { opacity: '1' },
          to: { opacity: '0' },
        },
      },
    },
  },
  plugins: [],
};
